### ISSUE TITLE
Stackoverflow error when using a nested property

### ISSUE THREAD

**Issue by denieus** [xvik/dropwizard-guicey#60]
**dropwizard version**: 1.3.12
**dropwizard-guicey version**: 4.2.2

If I have a configuration file with a property that contains itself I get a Stackoverflow error.

For instance, if I define this configuration file:

```yml
myCustomProperty:
  fieldA: valueA
  fieldB: valueB
  myCustomProperty:
    fieldA: valueA2
    fieldB: valueB2
```

And this configuration class:

```java
public class MyCustomProperty {

    @JsonProperty
    private String fieldA;
    @JsonProperty
    private String fieldB;
    @JsonProperty
    private MyCustomProperty myCustomProperty;
...
}
```

This will return a Stackoverflow in this line:

```
at ru.vyarus.dropwizard.guice.module.yaml.ConfigTreeBuilder.resolvePaths(ConfigTreeBuilder.java:192)
```
